[client]
socket="/mysqldata/mysql3306/mysql.sock"

[mysqld_multi]
mysqld="/usr/local/mysql/bin/mysqld_safe"
mysqladmin="/usr/local/mysql/bin/mysqladmin"
log="/mysqldata/mysqld_multi.log"
user="admin"
pass="zh3p8ch2we"

[mysqld_safe]
log_error="/mysqldata/mysql3306/log/mysqld.log"
pid-file="/mysqldata/mysql3306/mysql.pid"
datadir="/mysqldata/mysql3306/data/"
socket="/mysqldata/mysqld3306/mysql.sock"

[mysql]
default-character-set="utf8mb4"

[mysqld]
port="3306"
log_timestamps="SYSTEM"
basedir="/usr/local/mysql/"
datadir="/mysqldata/mysql3306/data/"
socket="/mysqldata/mysql3306/mysql.sock"
log_error="/mysqldata/mysql3306/log/mysqld.log"
pid-file="/mysqldata/mysql3306/mysql.pid"
secure_file_priv=" "

server-id="3306186130"
transaction-isolation="READ-COMMITTED"
character_set_server="utf8mb4"
open_files_limit=65535
lower_case_table_names=1
max_connections=2000
max_connect_errors="1844674407370954751"
connect_timeout=20
lock_wait_timeout=3600
thread_cache_size=64
sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

plugin_load="rpl_semi_sync_master=semi_sync_master.so;rpl_semi_sync_slave=semi_slave.so"
rpl_semi_sync_slave_enabled=1
rpl_semi_sync_master_wait_for_slave_count=1
rpl_semi_sync_master_wait_no_slave=1
rpl_semi_sync_master_timeout=1000000000

binlog_format="row"
log_bin="/mysqllog/mysql3306/binlog/mysql-bin"
max_binlog_size="1G"
expire_logs_days=1
binlog_error_action="ABORT_SERVER"

log_slave_updates=1
relay_log="/mysqllog/mysql3306/relaylog/mysql-relay"
max_relay_log_size="1G"
relay_log_purge=0

master_info_repository="TABLE"
relay_log_info_repository="TABLE"
relay_log_recovery=1
report_host="192.168.186.131"
report_port="3307"

sync_binlog=1
innodb_flush_log_at_trx_commit=1

innodb_buffer_pool_size="2048M"
innodb_sort_buffer_size="4M"
innodb_log_buffer_size="32M"
innodb_lock_wait_timeout=60
innodb_log_file_size="1G"
innodb_log_files_in_group=4
innodb_io_capacity=2000
innodb_io_capacity_max=4000
innodb_file_per_table=1
innodb_stats_persistent_sample_pages=64
innodb_online_alter_log_max_size="1G"
innodb_thread_concurrency=0
innodb_write_io_threads=16
innodb_read_io_threads=16
innodb_page_cleaners=8
innodb_flush_method="O_DIRECT"
innodb_monitor_enable="all"
innodb_print_all_deadlocks=1

gtid_mode="on"
enforce_gtid_consistency=1
slave-parallel-type="LOGICAL_CLOCK"
slave-parallel-workers=16
slave_preserve_commit_order=1
slave_transaction_retries=128
binlog_gtid_simple_recovery=1

loose_innodb_numa_interleave=1
innodb_buffer_pool_dump_pct=40
innodb_undo_logs=128
innodb_undo_log_truncate=0
innodb_max_undo_log_size="2G"
innodb_purge_rseg_truncate_frequency=128

max_allowed_packet="64M"
table_open_cache=2048
tmp_table_size="16M"
max_heap_table_size="16M"
sort_buffer_size="2M"
join_buffer_size="2M"
read_buffer_size="2M"
read_rnd_buffer_size="2M"
key_buffer_size="128M"
bulk_insert_buffer_size="64M"
binlog_cache_size="1M"

slow_query_log_file="/mysqldata/mysql3306/log/mysql-slow.log"
slow_query_log="OFF"
long_query_time=0.1
log_output="file"

performance_schema="ON"
performance-schema-instrument="'wait/lock/metadata/sql/mdl/memory=ON'"

symbolic-links=0
